apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rxaoupke
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-rxaoupke:40c97cec8ec495e63fa24cde9cc35589d8e409b3@sha256:a535eafb43b40c7d1a0cda28c5d1c50b42f58d39df79cd68124d9a67256799c3
          name: container-image
